package com.example.demo.apis;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNull;

class BookEntityTest {

    @Test
    void testDefaultConstructor() {
        BookEntity book = new BookEntity();

        // Verify that the default constructor initializes fields to null
        assertNull(book.getId());
        assertNull(book.getName());
        assertNull(book.getDescription());
    }

    @Test
    void testConstructorWithFields() {
        BookEntity book = new BookEntity("Sample Book", "Description");

        // Verify that the constructor sets the values correctly
        assertNull(book.getId()); // ID will be generated by the database
        assertEquals("Sample Book", book.getName());
        assertEquals("Description", book.getDescription());
    }

}


